/** アームドーザIDマスタ */
export const ArmdozerIds = {
  SHIN_BRAVER: "SHIN_BRAVER",
  NEO_LANDOZER: "NEO_LANDOZER",
  LIGHTNING_DOZER: "LIGHTNING_DOZER",
  WING_DOZER: "WING_DOZER",
  GENESIS_BRAVER: "GENESIS_BRAVER",
};
